services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    networks:
      - php-migrate
    environment:
      - MIGRATE=${MIGRATE_ENV}
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app/:/var/www/html/
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-migrate
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: seeds_db
      MYSQL_USER: seeds_user
      MYSQL_PASSWORD: seeds
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - php-migrate

networks:
  php-migrate:
    external: true
